---
# APT cache TTL in seconds.
apt_cache_valid_time: 3600

# List of packages to install.
podman_packages:
  - "podman"

podman_enable_binary_crun: "{{ ansible_facts.distribution == 'Ubuntu' and ansible_facts.distribution_version == '22.04' }}"
podman_binary_crun_url: "https://github.com/containers/crun/releases/download/1.14.4/crun-1.14.4-linux-amd64"

# Podman config variables
podman_storage_driver:
podman_runtime_directory:

# Podman can work with docker registries so it can stay this way
# URL of private registry
podman_registry:
podman_registry_insecure: false

# Podman registry mirror
podman_registry_mirror:

# Path to a CA file for registry
podman_registry_ca:
